name: knip

run-name: knip

on:
  push:
    branches:
      - "**"

jobs:
  knip:
    name: knip
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Enable corepack (workaround)
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: knip
        run: node_modules/.bin/knip
