name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run all
